version: '3'

services:
  api:
    image: ghcr.io/glo3112-classrooms/ugram-h2023-team-14/ugram_api:latest
    build:
      context: ${API_PATH}
      target: dev
    ports:
      - "3030:3030"
    environment:
      POSTGRES_HOST: "db"
      DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./api/src:/app/src
      - ./api/config:/app/config
      - ./api/test:/app/test
      - ./api/public:/app/public
    networks:
      - conection-db
  db:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - conection-db
    volumes:
      - db-data:/var/lib/postgresql/data

  client:
    image: ghcr.io/glo3112-classrooms/ugram-h2023-team-14/ugram_web:latest
    build:
      context: ${WEB_PATH}
      target: dev
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    restart: on-failure
    volumes:
      - ${WEB_PATH}/data:/app/data
      - ${WEB_PATH}/pages:/app/pages
      - ${WEB_PATH}/public:/app/public
      - ${WEB_PATH}/src:/app/src
      - ${WEB_PATH}/styles:/app/styles
      - ${WEB_PATH}/.env:/app/.env

networks:
  conection-db:

volumes:
  db-data:
